### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by urbanecm** [earwig/copyvios#27]
Hi, 
I've got following error. Reported as advised. 

Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 104, in index
    query = do_check()
  File "./copyvios/checker.py", line 38, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 86, in _get_results
    short_circuit=not query.noskip)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/__init__.py", line 127, in copyvio_check
    self._exclusions_db.sync(self.site.name)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/exclusions.py", line 164, in sync
    self._update(sitename)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/exclusions.py", line 138, in _update
    conn.execute(query7, (sitename, int(time())))
OperationalError: database is locked

Best, 
Martin Urbanec@cswiki

**Comment by urbanecm** [comment]
https://tools.wmflabs.org/copyvios/?lang=cs&project=wikipedia&title=Wikipedista%3ACzechMira%2FP%C3%ADskovi%C5%A1t%C4%9B&oldid=&action=search&use_engine=1&use_links=1&turnitin=0 was the used URL

**Comment by earwig** [comment]
Are you still noticing a problem? It seems to be working now.

**Comment by urbanecm** [comment]
No, it seems to be a temporary problem. Sorry for false-positive! BTW what does the message mean?

**Comment by earwig** [comment]
It probably means Labs is doing some maintenance on their end that prevents the tool from writing to its database file. Usually an intermittent sort of thing.
