### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by kenrick95** [earwig/copyvios#28]
Try to access [this](http://tools.wmflabs.org/copyvios/?lang=id&project=wikipedia&title=Tiyo_Avianto&oldid=&action=search&use_engine=1&use_links=1&turnitin=0).

Error message was:

```
Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
    query = do_check()
  File "./copyvios/checker.py", line 38, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 86, in _get_results
    short_circuit=not query.noskip)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/__init__.py", line 127, in copyvio_check
    self._exclusions_db.sync(self.site.name)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/exclusions.py", line 164, in sync
    self._update(sitename)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/exclusions.py", line 138, in _update
    conn.execute(query7, (sitename, int(time())))
OperationalError: database is locked
```

**Comment by earwig** [comment]
Intermittent. #27
