### ISSUE TITLE
Error on Benutzer:Munfarid1/Dinosaurier von Tendaguru

### ISSUE THREAD

**Issue by XenonX3** [earwig/copyvios#36]
Hi,

I repeatedly got an error on trying to use the Copyvio Detector on https://de.wikipedia.org/wiki/Benutzer:Munfarid1/Dinosaurier_von_Tendaguru. The following error message was shown:

```
Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
    query = do_check()
  File "./copyvios/checker.py", line 41, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 80, in _get_results
    _perform_check(query, page, use_engine, use_links)
  File "./copyvios/checker.py", line 136, in _perform_check
    short_circuit=not query.noskip)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/__init__.py", line 154, in copyvio_check
    workspace.enqueue(searcher.search(chunk), exclude)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/search.py", line 157, in search
    result = self._open(url + urlencode(params))
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/copyvios/search.py", line 61, in _open
    response = self.opener.open(*args)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 408, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```
Thx,
X

**Comment by earwig** [comment]
Are you still seeing this error? It seems to work when I run it, so perhaps the tool had an intermittent issue accessing Google when you were using it. If so, the error message should be improved, so I'll look at that separately.

**Comment by XenonX3** [comment]
It's working now, thanks!
