### ISSUE TITLE
This tools has problems with _ in article title

### ISSUE THREAD

**Issue by ferdi2005** [earwig/copyvios#40]
If I insert an article title with `_` copyvios raises this error:
```
Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
    query = do_check()
  File "./copyvios/checker.py", line 41, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 52, in _get_results
    page.get()  # Make sure that the page exists before we check it!
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/page.py", line 587, in get
    rvprop="content|timestamp", rvslots="main")
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 716, in api_query
    return self._api_query(kwargs)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 254, in _api_query
    return self._handle_api_result(response, params, tries, wait, ae_retry)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 295, in _handle_api_result
    raise exceptions.APIError(e)
APIError: API query failed: JSON could not be decoded.

```
<img width="1450" alt="Schermata 2019-08-16 alle 17 17 27" src="https://user-images.githubusercontent.com/19609180/63178213-de864d80-c049-11e9-91bd-144e1b58d9b1.png">

**Comment by ferdi2005** [comment]
It's fixable with a simple `title.str.replace('_', ' ')`, but I don't know where the page title variable is, Python apps are so obscure to me 😄

**Comment by earwig** [comment]
The _ is not the cause of the problem, but I've fixed the problem nonetheless. See #39.

**Comment by ferdi2005** [comment]
Ok, thanks. I associated it to _ because it was always (100%) when asking with _
