### ISSUE TITLE
Error when submitting Sodium diacetate

### ISSUE THREAD

**Issue by waddie96** [earwig/copyvios#41]
Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
    query = do_check()
  File "./copyvios/checker.py", line 41, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 80, in _get_results
    _perform_check(query, page, use_engine, use_links)
  File "./copyvios/checker.py", line 123, in _perform_check
    conn = get_db()
  File "./copyvios/misc.py", line 63, in get_db
    g._db = _connect_to_db(engine, args)
  File "./copyvios/misc.py", line 51, in _connect_to_db
    return oursql.connect(**args)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1546, in connect
    return self.get_pool(*args, **kw).connect()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 414, in connect
    return _ConnectionFairy._checkout(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 811, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 548, in checkout
    rec._checkin_failed(err)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 545, in checkout
    dbapi_connection = rec.get_connection()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 644, in get_connection
    self.__connect()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 690, in __connect
    connection = pool._invoke_creator(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 320, in <lambda>
    return lambda crec: creator()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1523, in <lambda>
    lambda: self.module.connect(*args, **kw), **self.kw
  File "oursqlx/connection.pyx", line 150, in oursql.Connection.__cinit__ (oursqlx/oursql.c:6455)
  File "oursqlx/connection.pyx", line 183, in oursql.Connection._raise_error (oursqlx/oursql.c:6984)
InterfaceError: (2003, "Can't connect to MySQL server on 'tools.labsdb' (113)", None)

**Comment by waddie96** [comment]
Seems similar to #19 ?

**Comment by earwig** [comment]
Cloud Services had a brief database server outage, and it should be resolved now. See https://phabricator.wikimedia.org/T236420.
