### ISSUE TITLE
API error blip

### ISSUE THREAD

**Issue by Arenlor** [earwig/copyvios#44]
Running again didn't give the error, so reporting so that it's logged:

> Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
    query = do_check()
  File "./copyvios/checker.py", line 41, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 46, in _get_results
    page = query.page = _get_page_by_revid(query.site, query.oldid)
  File "./copyvios/checker.py", line 104, in _get_page_by_revid
    rvslots="main")
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 707, in api_query
    return self._api_query(kwargs)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 247, in _api_query
    return self._handle_api_result(response, params, tries, wait, ae_retry)
  File "/data/project/copyvios/git/earwigbot/earwigbot/wiki/site.py", line 338, in _handle_api_result
    raise error
APIError: API query failed: got error "badinteger"; server says: "Invalid value "Akram Sheikh" for integer parameter "revids".".

**Comment by earwig** [comment]
This is likely due to putting the article title as the revision ID by mistake. I'll add some validation to give a better error message.

**Comment by earwig** [comment]
This is fixed now.
