### ISSUE TITLE
Crash on all searches, "Can't connect to MySQL server on tools.labsdb"

### ISSUE THREAD

**Issue by Rosguill** [earwig/copyvios#45]
When attempting searches, the page crashes with error code `InterfaceError: (2003, "Can't connect to MySQL server on 'tools.labsdb' (111)", None)`. This appears to occur regardless of which page is being searched, and whether or not "use search engine" and "use links in page" are selected.

This error occurred on Firefox 83.0, and also appears to be occurring within the NPP browser tool

Full error message:
```
Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
    query = do_check()
  File "./copyvios/checker.py", line 41, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 80, in _get_results
    _perform_check(query, page, use_engine, use_links)
  File "./copyvios/checker.py", line 123, in _perform_check
    conn = get_db()
  File "./copyvios/misc.py", line 63, in get_db
    g._db = _connect_to_db(engine, args)
  File "./copyvios/misc.py", line 51, in _connect_to_db
    return oursql.connect(**args)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1546, in connect
    return self.get_pool(*args, **kw).connect()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 414, in connect
    return _ConnectionFairy._checkout(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 811, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 543, in checkout
    rec = pool._do_get()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1239, in _do_get
    self._dec_overflow()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1236, in _do_get
    return self._create_connection()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 361, in _create_connection
    return _ConnectionRecord(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 488, in __init__
    self.__connect(first_connect_check=True)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 690, in __connect
    connection = pool._invoke_creator(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 320, in <lambda>
    return lambda crec: creator()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1523, in <lambda>
    lambda: self.module.connect(*args, **kw), **self.kw
  File "oursqlx/connection.pyx", line 150, in oursql.Connection.__cinit__ (oursqlx/oursql.c:6455)
  File "oursqlx/connection.pyx", line 183, in oursql.Connection._raise_error (oursqlx/oursql.c:6984)
InterfaceError: (2003, "Can't connect to MySQL server on 'tools.labsdb' (111)", None)
```

**Comment by Nathan2055** [comment]
A similar looking crash is happening on my end as well. I'm using Firefox 83.0 x64 on Windows 10 Pro 2004 x64. Only extension installed is uBlock Origin.

```
Traceback (most recent call last):
  File "/data/project/copyvios/www/python/src/app.py", line 38, in inner
    return func(*args, **kwargs)
  File "/data/project/copyvios/www/python/src/app.py", line 103, in index
    query = do_check()
  File "./copyvios/checker.py", line 41, in do_check
    _get_results(query, follow=not _coerce_bool(query.noredirect))
  File "./copyvios/checker.py", line 80, in _get_results
    _perform_check(query, page, use_engine, use_links)
  File "./copyvios/checker.py", line 123, in _perform_check
    conn = get_db()
  File "./copyvios/misc.py", line 63, in get_db
    g._db = _connect_to_db(engine, args)
  File "./copyvios/misc.py", line 51, in _connect_to_db
    return oursql.connect(**args)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1546, in connect
    return self.get_pool(*args, **kw).connect()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 414, in connect
    return _ConnectionFairy._checkout(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 811, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 543, in checkout
    rec = pool._do_get()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1239, in _do_get
    self._dec_overflow()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1236, in _do_get
    return self._create_connection()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 361, in _create_connection
    return _ConnectionRecord(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 488, in __init__
    self.__connect(first_connect_check=True)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 690, in __connect
    connection = pool._invoke_creator(self)
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 320, in <lambda>
    return lambda crec: creator()
  File "/data/project/copyvios/www/python/venv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1523, in <lambda>
    lambda: self.module.connect(*args, **kw), **self.kw
  File "oursqlx/connection.pyx", line 150, in oursql.Connection.__cinit__ (oursqlx/oursql.c:6455)
  File "oursqlx/connection.pyx", line 183, in oursql.Connection._raise_error (oursqlx/oursql.c:6984)
InterfaceError: (2003, "Can't connect to MySQL server on 'tools.labsdb' (111)", None)
```

**Comment by earwig** [comment]
https://lists.wikimedia.org/pipermail/cloud-announce/2020-December/000352.html

**Comment by earwig** [comment]
The issue should be resolved; let me know if it reoccurs.
